language: node_js
node_js:
  - "6.0"
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_REPO_TOKEN
after_success:
  - yarn add global codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
